# -*- coding: utf-8 -*-
"""avlanache_data_extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVHtBHwPg5u_n9SkZ-mkwQbrGTGRftEO
"""

#from google.colab import drive
#drive.mount('/content/drive')

import pandas as pd
from regobslib import *
import datetime as dt

#NotebookApp.iopub_data_rate_limit=1.0e10

START = dt.date(2017, 11, 1)
STOP = dt.date(2023, 9, 30)
#REGIONS = [SnowRegion.HARDANGER]

connection = Connection(prod=True)

varsom = connection.get_varsom(START, STOP)

danger_levels = varsom.to_danger_level_series()

problems = varsom.to_problem_frame(with_priorities=True)

forecast_df = pd.concat([danger_levels], axis=1)

forecast_df.to_csv("/PATH_TO_AVALANCHE_RISK/Avalanche_Risk_List.csv")

problems.to_csv("/PATH_TO_AVALANCHE_PROBLEM/Avalanche_Problems_List.csv")